#!/bin/sh

# This script runs percollator.se with the proper options for our site.

# Set this variable.
STATSDIR=/home/bzajac/Code/MRTG/bzajac/percollator

# Kill any running percollators.
$STATSDIR/bin/stop_percol

# Start the percollator.
$STATSDIR/bin/start_percol
